# Generated by Django 4.2 on 2024-01-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_transaction_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
